media: static/images/uploads

content:
  posts:
    name: Posts
    path: content/posts
    type: collection
    fields:
      - name: title
        label: Título
        type: string
      - name: date
        label: Fecha
        type: date
      - name: author
        label: Autor
        type: string
      - name: categories
        label: Categorías
        type: list
      - name: tags
        label: Etiquetas
        type: list
      - name: summary
        label: Resumen
        type: text
      - name: body
        label: Contenido
        type: rich-text

  estadisticas:
    name: Estadísticas Sanitarias
    path: content/estadisticas
    type: collection
    fields:
      - name: title
        label: Título
        type: string
      - name: fuente
        label: Fuente de datos
        type: string
      - name: anio
        label: Año del análisis
        type: number
      - name: body
        label: Contenido
        type: rich-text

  pages:
    name: Páginas
    path: content
    type: collection
    exclude: [posts, estadisticas]
    fields:
      - name: title
        label: Título
        type: string
      - name: body
        label: Contenido
        type: rich-text
